// Automatically generated by https://honeythecodewitch.com/gfx/icon-pack
// #define CONNECT_IMPLEMENTATION in exactly one
// translation unit (.cpp file) before including this header
#ifndef CONNECT_HPP
#define CONNECT_HPP
#include <stdint.h>
#include <stddef.h>
#include "gfx_core.hpp"
#include "gfx_positioning.hpp"

constexpr static const uint16_t connect_height = 32;

/// @brief "Wifi" dimensions
constexpr static const gfx::sizef connect_wifi_dimensions(640,512);
/// @brief "Wifi" scaled dimensions
constexpr static const gfx::size16 connect_wifi_scaled_dimensions(40,32);
/// @brief "Wifi" target scale
constexpr static const float connect_wifi_scale = 0.0625;
/// @brief "Wifi" - a SVG vector icon
extern gfx::const_buffer_stream connect_wifi;
#endif // CONNECT_HPP

#ifdef CONNECT_IMPLEMENTATION
static const char* connect_wifi_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewB"
    "ox=\"0 0 640 512\"><path d=\"M54.2 202.9C123.2 136.7 216.8 96 320 96s196.8 40.7 265"
    ".8 106.9c12.8 12.2 33 11.8 45.2-.9s11.8-33-.9-45.2C549.7 79.5 440.4 32 320 32S90"
    ".3 79.5 9.8 156.7C-2.9 169-3.3 189.2 8.9 202s32.5 13.2 45.2 .9zM320 256c56.8 0 1"
    "08.6 21.1 148.2 56c13.3 11.7 33.5 10.4 45.2-2.8s10.4-33.5-2.8-45.2C459.8 219.2 3"
    "93 192 320 192s-139.8 27.2-190.5 72c-13.3 11.7-14.5 31.9-2.8 45.2s31.9 14.5 45.2"
    " 2.8c39.5-34.9 91.3-56 148.2-56zm64 160a64 64 0 1 0 -128 0 64 64 0 1 0 128 0z\"/>"
    "</svg>";
gfx::const_buffer_stream connect_wifi
    ((const uint8_t*)connect_wifi_data, 531);
#endif // CONNECT_IMPLEMENTATION
